package atlas;

import java.awt.Desktop;
import java.io.File;

import atlas.scanner.FileScanner;
import atlas.scanner.ScanProgress;
import atlas.scanner.ScanResult;

public class AtlasMenu {


    /*
     * ============================================================
     * UPDATE
     * ============================================================
     *
     * Handles changes that happen without user input.
     *
     * The biggest example is a scan finishing.
     */
    public static void update(
        AtlasState state
    ) {

        /*
         * A scan has finished and its result hasn't
         * been processed by the UI yet.
         */
        if (
            !state.scanRunning.get()
            && state.scanResult != null
        ) {

            if (state.cancelScanRequested.get()) {

                state.lastMessage =
                    "Scan cancelled.\n" +
                    "Files Found: " +
                    state.scanResult.getFilesFound() +
                    "\nFolders Found: " +
                    state.scanResult.getFoldersFound() +
                    "\nSkipped: " +
                    state.scanResult.getSkippedFound();

            }

            else {

                state.lastMessage =
                    "Scan complete.\n" +
                    "Files Found: " +
                    state.scanResult.getFilesFound() +
                    "\nFolders Found: " +
                    state.scanResult.getFoldersFound() +
                    "\nSkipped: " +
                    state.scanResult.getSkippedFound();
            }


            /*
             * The result has now been converted into
             * a UI message.
             */
            state.scanResult = null;

            state.cancelScanRequested.set(false);

            state.uiScanning = false;

            state.uiNeedsRender = true;
        }
    }



    /*
     * ============================================================
     * RENDER
     * ============================================================
     *
     * The main thread is the ONLY thread that calls this.
     */
    public static void renderIfNeeded(
        AtlasState state
    ) {

        if (!state.uiNeedsRender) {

            return;
        }


        System.out.println();


        /*
         * Print any message generated by a command
         * or by an automatic state change.
         */
        if (!state.lastMessage.isEmpty()) {

            System.out.println(
                state.lastMessage
            );

            System.out.println();

            state.lastMessage = "";
        }


        /*
         * Scanner UI
         */
        if (
            state.uiScanning
            && state.cancelScanRequested.get()
        ) {

            /*
             * Cancellation already requested — nothing
             * more to show until the scan finishes.
             */
        }

        else if (state.uiScanning) {

            System.out.println(
                "Scanner is still running...\n"
            );

            System.out.println(
                "Scanner options:"
            );

            System.out.println(
                "progress"
            );

            System.out.println(
                "cancel"
            );

            System.out.println(
                "\nEnter command: "
            );
        }


        /*
         * Normal Atlas UI
         */
        else {

            System.out.println(
                "Current Path: " +
                state.currentPath
            );

            System.out.println();

            System.out.println(
                "Menu:"
            );

            System.out.println(
                "show root\n" +
                "show current\n" +
                "open {name}\n" +
                "parent dir\n" +
                "scan\n" +
                "exit\n\n" +
                "Enter command: "
            );
        }


        state.uiNeedsRender = false;
    }



    /*
     * ============================================================
     * COMMAND ROUTING
     * ============================================================
     */
    public static String handleCommand(
        String input,
        AtlasState state,
        FileScanner fileScanner
    ) {

        /*
         * Scanner mode.
         */
        if (state.uiScanning) {

            return handleScannerCommand(
                input,
                state
            );
        }


        /*
         * Normal Atlas mode.
         */
        return handleNormalCommand(
            input,
            state,
            fileScanner
        );
    }



    /*
     * ============================================================
     * SCANNER COMMANDS
     * ============================================================
     */
    private static String handleScannerCommand(
        String input,
        AtlasState state
    ) {

        if (input.equals("progress")) {

            return showProgress(state);
        }


        else if (input.equals("cancel")) {

            cancelScan(state);

            return "";
        }


        else {

            return
                "Scanner is still running. \n" +
                "Use 'progress' or 'cancel'.";
        }
    }



    /*
     * ============================================================
     * NORMAL ATLAS COMMANDS
     * ============================================================
     */
    private static String handleNormalCommand(
        String input,
        AtlasState state,
        FileScanner fileScanner
    ) {

        if (input.equals("show root")) {

            showRoot();

            return "";
        }


        else if (input.equals("show current")) {

            showCurrent(state);

            return "";
        }


        else if (input.startsWith("open ")) {

            String itemName =
                input.substring(5);

            openItem(
                itemName,
                state
            );

            return "";
        }


        else if (input.equals("parent dir")) {

            parentDir(state);

            return "";
        }


        else if (input.equals("scan")) {

            startScan(
                state,
                fileScanner
            );

            return "Scanner started.";
        }


        else if (input.equals("exit")) {

            return "exit";
        }


        else {

            return "Invalid input.";
        }
    }



    /*
     * ============================================================
     * START SCAN
     * ============================================================
     */
    private static void startScan(
        AtlasState state,
        FileScanner fileScanner
    ) {

        state.cancelScanRequested.set(false);

        state.scanRunning.set(true);

        state.uiScanning = true;

        state.scanResult = null;


        ScanProgress progress =
            new ScanProgress();

        state.scanProgress =
            progress;


        Thread scanThread =
            new Thread(() -> {

                ScanResult result =
                    fileScanner.scan(
                        state.currentPath,
                        progress,
                        state.cancelScanRequested
                    );


                /*
                 * Scan thread ONLY updates state.
                 *
                 * It does NOT print anything.
                 */
                state.scanResult =
                    result;

                state.scanRunning.set(false);

            }, "Atlas-Scanner");


        scanThread.start();
    }



    /*
     * ============================================================
     * PROGRESS
     * ============================================================
     */
    private static String showProgress(
        AtlasState state
    ) {

        if (state.scanProgress == null) {

            return "No scan progress available.";
        }


        return
            "Files Found: " +
            state.scanProgress.getFilesFound() +

            "\nFolders Found: " +
            state.scanProgress.getFoldersFound() +

            "\nSkipped: " +
            state.scanProgress.getSkippedFound() +

            "\nCurrent: " +
            state.scanProgress.getCurrentPath();
    }



    /*
     * ============================================================
     * ROOT
     * ============================================================
     */
    private static void showRoot() {

        File directory =
            new File("\\");

        File[] items =
            directory.listFiles();


        if (items == null) {

            System.out.println(
                "Unable to access root directory."
            );

            return;
        }


        for (File item : items) {

            if (item.isFile()) {

                System.out.println(
                    item.getName()
                );
            }

            else if (item.isDirectory()) {

                System.out.println(
                    "\\" +
                    item.getName()
                );
            }
        }
    }



    /*
     * ============================================================
     * CURRENT DIRECTORY
     * ============================================================
     */
    private static void showCurrent(
        AtlasState state
    ) {

        File directory =
            state.currentPath.toFile();

        File[] items =
            directory.listFiles();


        if (items == null) {

            System.out.println(
                "Unable to access: " +
                state.currentPath
            );

            return;
        }


        for (File item : items) {

            if (item.isFile()) {

                System.out.println(
                    item.getName()
                );
            }

            else if (item.isDirectory()) {

                System.out.println(
                    "\\" +
                    item.getName()
                );
            }
        }
    }



    /*
     * ============================================================
     * OPEN ITEM
     * ============================================================
     */
    private static void openItem(
        String itemName,
        AtlasState state
    ) {

        File item =
            state.currentPath
                .resolve(itemName)
                .toFile();


        if (!item.exists()) {

            state.lastMessage =
                "This item doesn't exist in this directory.";

            state.uiNeedsRender = true;

            return;
        }


        /*
         * Opening a file means opening it with the
         * operating system.
         */
        if (item.isFile()) {

            try {

                Desktop.getDesktop().open(item);

            }

            catch (Exception e) {

                state.lastMessage =
                    "Error opening file " +
                    item +
                    ": " +
                    e.getMessage();

                state.uiNeedsRender = true;
            }

            return;
        }


        /*
         * Opening a directory only changes our
         * current path.
         */
        if (item.isDirectory()) {

            state.currentPath =
                item.toPath();

            state.uiNeedsRender = true;
        }
    }



    /*
     * ============================================================
     * PARENT DIRECTORY
     * ============================================================
     */
    private static void parentDir(
        AtlasState state
    ) {

        if (
            state.currentPath.getParent() != null
        ) {

            state.currentPath =
                state.currentPath.getParent();

            state.uiNeedsRender = true;
        }

        else {

            state.lastMessage =
                "Already at root dir!";

            state.uiNeedsRender = true;
        }
    }



    /*
     * ============================================================
     * CANCEL SCAN
     * ============================================================
     */
    private static void cancelScan(
        AtlasState state
    ) {

        /*
         * Do NOT wait for the scanner here.
         *
         * We simply request cancellation.
         */
        state.cancelScanRequested.set(true);


        state.lastMessage =
            "Cancellation requested...";


        state.uiNeedsRender = true;
    }
}