package atlas;

import atlas.scanner.FileScanner;
import atlas.scanner.ScanUtils;

public class AtlasMenu {


    /*
     * ============================================================
     * UPDATE
     * ============================================================
     *
     * Handles changes that happen without user input.
     *
     * The biggest example is a scan finishing.
     */
    public static void update(
        AtlasState state
    ) {

        /*
         * A scan has finished and its result hasn't
         * been processed by the UI yet.
         */
        if (
            !state.scanRunning.get()
            && state.scanResult != null
        ) {

            if (state.cancelScanRequested.get()) {

                state.lastMessage =
                    "Scan cancelled.\n" +
                    "Files Found: " +
                    state.scanResult.getFilesFound() +
                    "\nFolders Found: " +
                    state.scanResult.getFoldersFound() +
                    "\nSkipped: " +
                    state.scanResult.getSkippedFound();

            }

            else {

                state.lastMessage =
                    "Scan complete.\n" +
                    "Files Found: " +
                    state.scanResult.getFilesFound() +
                    "\nFolders Found: " +
                    state.scanResult.getFoldersFound() +
                    "\nSkipped: " +
                    state.scanResult.getSkippedFound();
            }


            /*
             * The result has now been converted into
             * a UI message.
             */
            state.scanResult = null;

            state.cancelScanRequested.set(false);

            state.uiScanning = false;

            state.uiNeedsRender = true;
        }
    }



    /*
     * ============================================================
     * RENDER
     * ============================================================
     *
     * The main thread is the ONLY thread that calls this.
     */
    public static void renderIfNeeded(
        AtlasState state
    ) {

        if (!state.uiNeedsRender) {

            return;
        }


        System.out.println();


        /*
         * Print any message generated by a command
         * or by an automatic state change.
         */
        if (!state.lastMessage.isEmpty()) {

            System.out.println(
                state.lastMessage
            );

            System.out.println();

            state.lastMessage = "";
        }


        /*
         * Scanner UI
         */
        if (
            state.uiScanning
            && state.cancelScanRequested.get()
        ) {

            /*
             * Cancellation already requested — nothing
             * more to show until the scan finishes.
             */
        }

        else if (state.uiScanning) {

            System.out.println(
                "Scanner is still running...\n"
            );

            System.out.println(
                "Scanner options:"
            );

            System.out.println(
                "progress"
            );

            System.out.println(
                "cancel"
            );

            System.out.println(
                "\nEnter command: "
            );
        }


        /*
         * Normal Atlas UI
         */
        else {

            System.out.println(
                "Current Path: " +
                state.currentPath
            );

            System.out.println();

            System.out.println(
                "Menu:"
            );

            System.out.println(
                "show root\n" +
                "show current\n" +
                "open {name}\n" +
                "parent dir\n" +
                "scan\n" +
                "exit\n\n" +
                "Enter command: "
            );
        }


        state.uiNeedsRender = false;
    }



    /*
     * ============================================================
     * COMMAND ROUTING
     * ============================================================
     */
    public static String handleCommand(
        String input,
        AtlasState state,
        FileScanner fileScanner
    ) {

        /*
         * Scanner mode.
         */
        if (state.uiScanning) {

            return handleScannerCommand(
                input,
                state
            );
        }


        /*
         * Normal Atlas mode.
         */
        return handleNormalCommand(
            input,
            state,
            fileScanner
        );
    }



    /*
     * ============================================================
     * SCANNER COMMANDS
     * ============================================================
     */
    private static String handleScannerCommand(
        String input,
        AtlasState state
    ) {

        if (input.equals("progress")) {

            return ScanUtils.showProgress(state);
        }


        else if (input.equals("cancel")) {

            ScanUtils.cancelScan(state);

            return "";
        }


        else {

            return
                "Scanner is still running. \n" +
                "Use 'progress' or 'cancel'.";
        }
    }



    /*
     * ============================================================
     * NORMAL ATLAS COMMANDS
     * ============================================================
     */
    private static String handleNormalCommand(
        String input,
        AtlasState state,
        FileScanner fileScanner
    ) {

        if (input.equals("show root")) {

            DirectoryBrowser.showRoot();

            return "";
        }


        else if (input.equals("show current")) {

            DirectoryBrowser.showCurrent(state);

            return "";
        }


        else if (input.startsWith("open ")) {

            String itemName =
                input.substring(5);

            DirectoryBrowser.openItem(
                itemName,
                state
            );

            return "";
        }


        else if (input.equals("parent dir")) {

            DirectoryBrowser.parentDir(state);

            return "";
        }


        else if (input.equals("scan")) {

            ScanUtils.startScan(
                state,
                fileScanner
            );

            return "Scanner started.";
        }


        else if (input.equals("exit")) {

            return "exit";
        }


        else {

            return "Invalid input.";
        }
    }


    


}